// Package handlers contains all HTTP handler implementations for the API.
package handlers

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/opencode-ai/polaris/internal/model"
	"github.com/opencode-ai/polaris/internal/services"
)

type ConfigHandler struct {
	configSvc *services.ConfigService
	statsSvc  *services.StatsService
}

func NewConfigHandler(configSvc *services.ConfigService) *ConfigHandler {
	return &ConfigHandler{configSvc: configSvc}
}

// SetStatsService sets the stats service for admin stats endpoints.
func (h *ConfigHandler) SetStatsService(statsSvc *services.StatsService) {
	h.statsSvc = statsSvc
}

// GetConfig returns the current site configuration
// @Summary      Get site config
// @Description  Returns the full site configuration for admin management
// @Tags         admin, config
// @Success      200 {object} model.SiteConfig
// @Failure      500 {object} map[string]interface{}
// @Router       /admin/config [get]
func (h *ConfigHandler) GetConfig(c *gin.Context) {
	cfg, err := h.configSvc.Get(c.Request.Context())
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, cfg)
}

// UpdateConfig updates the site configuration
// @Summary      Update site config
// @Description  Updates site configuration values. Only provided fields are changed (partial update).
// @Tags         admin, config
// @Accept       json
// @Produce      json
// @Param        body body model.UpdateConfigRequest true "Configuration fields to update"
// @Success      200 {object} model.SiteConfig
// @Failure      400 {object} map[string]interface{} "invalid request body"
// @Failure      500 {object} map[string]interface{}
// @Router       /admin/config [put]
func (h *ConfigHandler) UpdateConfig(c *gin.Context) {
	var req model.UpdateConfigRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	cfg, err := h.configSvc.Update(c.Request.Context(), req)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, cfg)
}

// GenerateInvite creates a new user invite
// @Summary      Generate invite
// @Description  Generates a new invite code for the authenticated user, subject to monthly limits
// @Tags         admin, invites
// @Accept       json
// @Produce      json
// @Success      201 {object} model.UserInvite
// @Failure      403 {object} map[string]interface{} "no invites remaining this month"
// @Failure      500 {object} map[string]interface{}
// @Router       /admin/invites [post]
func (h *ConfigHandler) GenerateInvite(c *gin.Context) {
	userID, _ := c.Get("user_id")

	invite, err := h.configSvc.GenerateInvite(c.Request.Context(), userID.(int64))
	if err != nil {
		if err == model.ErrForbidden {
			c.JSON(http.StatusForbidden, gin.H{"error": "no invites remaining this month"})
			return
		}
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusCreated, invite)
}

// ListInvites lists invites created by the authenticated user
// @Summary      List my invites
// @Description  Returns a paginated list of invite codes generated by the authenticated user
// @Tags         admin, invites
// @Produce      json
// @Success      200 {object} model.PaginatedResponse "paginated list of UserInvite"
// @Failure      500 {object} map[string]interface{}
// @Router       /admin/invites [get]
func (h *ConfigHandler) ListInvites(c *gin.Context) {
	userID, _ := c.Get("user_id")

	invites, err := h.configSvc.ListMyInvites(c.Request.Context(), userID.(int64))
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	if invites == nil {
		invites = []*model.UserInvite{}
	}
	c.JSON(http.StatusOK, model.NewPaginated(invites, 1, len(invites), len(invites)))
}

// GetInviteLimit returns the authenticated user's invite limit and usage
// @Summary      Get invite limit
// @Description  Returns how many invites the user can generate this month and how many have been used
// @Tags         admin, invites
// @Produce      json
// @Success      200 {object} map[string]interface{} "limit and used fields"
// @Failure      500 {object} map[string]interface{}
// @Router       /admin/invites/limit [get]
func (h *ConfigHandler) GetInviteLimit(c *gin.Context) {
	userID, _ := c.Get("user_id")

	limit, err := h.configSvc.GetInviteLimit(c.Request.Context(), userID.(int64))
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	count, err := h.configSvc.InviteCountThisMonth(c.Request.Context(), userID.(int64))
	if err != nil {
		count = 0
	}

	c.JSON(http.StatusOK, gin.H{
		"limit": limit,
		"used":  count,
	})
}

// GetStats returns aggregate system statistics for the admin panel.
// @Summary      Get system stats
// @Description  Returns aggregate system statistics for the admin dashboard
// @Tags         admin
// @Success      200 {object} model.AdminStats
// @Failure      500 {object} map[string]interface{}
// @Router       /admin/stats [get]
func (h *ConfigHandler) GetStats(c *gin.Context) {
	if h.statsSvc == nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "stats service not initialized"})
		return
	}
	stats, err := h.statsSvc.GetStats(c.Request.Context())
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, stats)
}
